# Generated by Django 5.1.5 on 2026-03-04 03:16

from django.db import migrations
from django.utils import timezone


def activate_existing_superusers(apps, schema_editor):
    """Set is_active=True and email_verified_at for existing superusers/staff so they can log in."""
    User = apps.get_model('users', 'User')
    now = timezone.now()
    updated = User.objects.filter(is_superuser=True).update(
        is_active=True,
        email_verified_at=now,
    )
    # Also activate staff users who might not be superuser
    staff_updated = User.objects.filter(is_staff=True, is_active=False).update(
        is_active=True,
        email_verified_at=now,
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.RunPython(activate_existing_superusers, noop),
    ]
