# Generated by Django 5.1.5 on 2026-01-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, db_index=True, help_text='Token for email verification. Cleared after verification.', max_length=64, null=True),
        ),
    ]
