# Generated by Django 5.2.7 on 2025-11-06 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_deleted",
        ),
    ]
