# Generated by Django 6.0 on 2025-12-04 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Public course title', max_length=255)),
                ('course_code', models.CharField(db_index=True, help_text='Human-readable unique code: PY101, WEB202, etc.', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Full course description (supports Markdown)')),
                ('image_url', models.URLField(blank=True, help_text='Course thumbnail/cover image (e.g., Cloudinary, S3, YouTube thumbnail)', max_length=500)),
                ('video_url', models.URLField(blank=True, help_text='Intro/promo video (YouTube, Vimeo, direct MP4 link). Shown on course detail page.', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='draft', help_text='Controls visibility and enrollment rules', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Quick toggle to show/hide course')),
                ('max_students', models.PositiveIntegerField(blank=True, help_text='Maximum enrollment limit. Leave empty for unlimited.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Used for filtering in mobile app and course list', related_name='courses', to='categories.category')),
                ('instructor', models.ForeignKey(help_text='Instructor who owns this course', limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course_code'], name='courses_course__5da9ef_idx'), models.Index(fields=['status', 'is_active'], name='courses_status_581bd2_idx')],
            },
        ),
    ]
