# Generated by Django 6.0 on 2025-12-09 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(db_index=True, help_text='Human-readable unique code: PY101, WEB202, etc.', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Quick toggle to show/hide course. Set to False for soft delete.'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('course_code',), name='unique_active_course_code'),
        ),
    ]
