# Generated by Django 6.0 on 2025-12-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_course_code_alter_course_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_active_course_code',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(db_index=True, help_text='Human-readable unique code: PY101, WEB202, etc.', max_length=20, unique=True),
        ),
    ]
