# Generated by Django 5.2.10 on 2026-01-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_unique_active_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_auto_enrolled',
            field=models.BooleanField(db_index=True, default=False, help_text='Automatically enroll new users in this course (e.g., for introduction courses).'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_introduction',
            field=models.BooleanField(db_index=True, default=False, help_text="Labels this course as 'Introductory' level. Used for UI filtering and the 'Recommended for Beginners' section."),
        ),
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, help_text='Course thumbnail/cover image (e.g., Cloudinary, S3, YouTube thumbnail)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='Intro/promo video (YouTube, Vimeo, direct MP4 link). Shown on course detail page.', max_length=700),
        ),
    ]
