# Generated by Django 5.2.10 on 2026-01-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_is_auto_enrolled_course_is_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_full_notified',
            field=models.BooleanField(default=False),
        ),
    ]
