# Generated by Django 5.2.10 on 2026-01-26 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('courses', '0006_remove_current_enrollment_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_introduction', 'is_active', 'status'], name='courses_is_intr_c3b6d4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_auto_enrolled', 'is_active'], name='courses_is_auto_6e6d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor', 'is_active'], name='courses_instruc_43dca9_idx'),
        ),
    ]
