# Generated by Django 5.2.7 on 2025-10-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_alter_course_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="video_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
