# Generated by Django 5.2.7 on 2025-11-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_course_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="card_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
