# Generated by Django 5.2.7 on 2025-11-03 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_course_card_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="card_image_url",
            new_name="image_url",
        ),
    ]
