# Generated by Django 5.2.7 on 2025-11-06 02:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


def migrate_category_data(apps, schema_editor):
    """
    Migrate existing category strings to Category model.
    """
    Course = apps.get_model("courses", "Course")
    Category = apps.get_model("courses", "Category")
    db_alias = schema_editor.connection.alias

    # Get all unique category strings from existing courses
    # At this point, category is still CharField, category_new is ForeignKey
    courses = Course.objects.using(db_alias).all()
    category_names = set()
    for course in courses:
        # Access the old category CharField directly from the database
        old_category_value = getattr(course, "category", None)
        if old_category_value and old_category_value.strip():
            category_names.add(old_category_value.strip())

    # Create Category objects for each unique category name
    category_map = {}
    for name in category_names:
        if name:  # Skip empty strings
            category, created = Category.objects.using(db_alias).get_or_create(
                name=name, defaults={"is_active": True}
            )
            category_map[name] = category

    # Update courses to reference the new Category objects via category_new field
    for course in courses:
        old_category_value = getattr(course, "category", None)
        if old_category_value and old_category_value.strip() in category_map:
            course.category_new = category_map[old_category_value.strip()]
            course.save(using=db_alias)


def reverse_migrate_category_data(apps, schema_editor):
    """
    Reverse migration: convert Category objects back to strings.
    Note: This is a simplified reverse - in practice, you'd need to restore the CharField first.
    """
    Course = apps.get_model("courses", "Course")
    db_alias = schema_editor.connection.alias

    # Convert category_new ForeignKey back to string in category field
    # Note: This assumes category CharField will be restored in reverse operations
    for course in Course.objects.using(db_alias).all():
        if course.category_new:
            # This will be handled by the reverse field operations
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_rename_card_image_url_course_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        # Add temporary field to store category ForeignKey
        migrations.AddField(
            model_name="course",
            name="category_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses_temp",
                to="courses.category",
            ),
        ),
        # Migrate data from old category to new category
        migrations.RunPython(migrate_category_data, reverse_migrate_category_data),
        # Remove old category field
        migrations.RemoveField(
            model_name="course",
            name="category",
        ),
        # Rename category_new to category
        migrations.RenameField(
            model_name="course",
            old_name="category_new",
            new_name="category",
        ),
    ]
