# Generated by Django 5.2.7 on 2025-11-06 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_remove_course_category_course_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="is_deleted",
        ),
    ]
