# Generated by Django 5.2.10 on 2026-01-22 04:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('STUDENT_ENROLLED', 'Student Enrolled'), ('COURSE_CAPACITY', 'Course Full'), ('STUDENT_REMOVED', 'Student Removed'), ('COURSE_UPDATED', 'Course Updated'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement')], db_index=True, help_text='The category of the alert (e.g., ENROLLMENT, ALERT, SYSTEM).', max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'recipient'], name='notificatio_type_0c6de8_idx'),
        ),
    ]
