# Generated by Django 5.2.10 on 2026-01-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('STUDENT_ENROLLED', 'Student Enrolled'), ('STUDENT_REMOVED', 'Student Removed'), ('COURSE_FULL', 'Course Full')], db_index=True, help_text='The category of the alert (e.g., ENROLLMENT, ALERT, SYSTEM).', max_length=50),
        ),
    ]
