[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
testpaths = tests
addopts =
    --create-db
    --nomigrations
    --cov=users
    --cov=courses
    --cov=categories
    --cov=enrollments
    --cov=core
    --cov=notifications
    --cov=reports
    --cov-report=html
    --cov-report=term-missing
    --cov-report=xml
    --cov-fail-under=85
    -v
