# Generated by Django 5.2.7 on 2025-10-30 02:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_alter_course_options"),
        ("enrollments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollment",
            options={"ordering": ["-enrolled_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("user", "course")},
        ),
    ]
