# Generated by Django 5.2.7 on 2025-11-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollments", "0002_alter_enrollment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
